### ISSUE TITLE
Fix improper sidebar menu logic

### ISSUE THREAD

**Issue by Ibrahimsyah** [Dynapgen/dynapgen.github.io#7]
### Background
We want to create a dynamic sidebar with this structure

Dashboard page:
- Apps -> /
- History -> /history

Main App Page:
- Apps -> /
- Content -> /apps/:app_id/content
- Monetization -> /apps/:app_id/monetization
- Build -> /apps/:app_id/build

![Image](https://user-images.githubusercontent.com/7591715/236729565-e805c01c-29da-4700-8551-f8c403d21f5b.png)

**Comment by kevinstewartsmith** [comment]
<img width="689" alt="Screen Shot 2023-05-08 at 7 44 52 PM" src="https://user-images.githubusercontent.com/29442789/236827481-9b343d2c-578e-4dde-9584-c9e13f66d897.png">

Like thus?

**Comment by Ibrahimsyah** [comment]
> <img alt="Screen Shot 2023-05-08 at 7 44 52 PM" width="689" src="https://user-images.githubusercontent.com/29442789/236827481-9b343d2c-578e-4dde-9584-c9e13f66d897.png">
> 
> Like this?

Thanks for the response. I Think the issue title is wrong. It should be sidebar instead of navbar. My bad.
We want to make the sidebar menu works like the description above
